In [ ]:
import cv2
import os


In [ ]:
#reading the files  from labels and saving to list
path=r"D:\work\ML\image_processing\YOLO V8\dataset\labels"
list1=os.listdir(path)

In [ ]:
list1=list1[1:]

In [ ]:
list1[0]

In [ ]:
len(list1)

In [ ]:
import shutil

In [ ]:
temp=[]
for i in list1:
    item=i.split(".")[0]
    temp.append(item)


In [ ]:
#reading the images
img_path=r"D:\work\ML\image_processing\YOLO V8\dataset\input"
trg=r"D:\work\ML\image_processing\YOLO V8\dataset\input_2"
c=0
for i in temp:
    item=i
    shutil.copy(img_path+"\\"+item+".jpg",trg+"\\"+item+".jpg")
    # print(i)
    # if c==10:
    #     break
    # c+=1


In [3]:
from  ultralytics import YOLO 
import cv2

In [4]:
import numpy as np

In [5]:
model=YOLO("best.pt")

In [22]:
import os
os.getcwd()

'd:\\work\\ML\\image_processing\\YOLO V8\\dataset'

In [23]:
# for i in range(7990,8000):
#     path=f"D:\work\ML\image_processing\YOLO V8\dataset\input\img_{i}.jpg"
#     result=model.predict(source=path, show=True)
#     cv2.waitKey(0)

In [24]:
print(r"D:\work\ML\image_processing\YOLO V8\dataset\input\img_7992.jpg")

D:\work\ML\image_processing\YOLO V8\dataset\input\img_7992.jpg


In [25]:
#read image and get box vectore
path=f"D:\work\ML\image_processing\YOLO V8\dataset\input\img_9995.jpg"
frame=cv2.imread(path)

In [41]:
result=model.predict(source=path, show=True)
cv2.waitKey(0)


image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_9995.jpg: 640x448 1 head, 1 body, 156.6ms
Speed: 3.0ms preprocess, 156.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)


-1

In [42]:
result[0]

ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'head', 1: 'body'}
obb: None
orig_img: array([[[ 33,  28,  27],
        [ 51,  46,  45],
        [ 59,  55,  54],
        ...,
        [251, 246, 243],
        [251, 246, 243],
        [251, 246, 243]],

       [[ 31,  23,  23],
        [ 45,  40,  39],
        [ 54,  49,  48],
        ...,
        [251, 246, 243],
        [251, 246, 243],
        [251, 246, 243]],

       [[ 37,  28,  25],
        [ 48,  41,  38],
        [ 56,  51,  48],
        ...,
        [251, 246, 243],
        [251, 246, 243],
        [251, 246, 243]],

       ...,

       [[147, 139, 122],
        [149, 141, 124],
        [133, 125, 108],
        ...,
        [133, 118, 102],
        [132, 117, 101],
        [128, 113,  97]],

       [[117, 109,  92],
        [121, 113,  96],
        [107,  99,  82],
        ...,
        [128, 113,  97],
        [130, 115,  99],
    

In [43]:
xyxy=result[0].boxes.xyxy[1]
print(xyxy)
frame=result[0].orig_img
frame=cv2.rectangle(frame,  (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (0,255,0), 1)
cv2.imshow("img",frame)
cv2.waitKey(0)

tensor([164.5233,  90.6473, 227.2965, 169.1569])


-1

In [45]:
def get_img_part(img,arr):
    """
    img: original image 
    arr: cordinates for subdivision
    """
    return img[arr[1]:arr[3],arr[0]:arr[2]]

In [46]:
#computing average head and body height
head_height=0
head_width=0
body_height=0
body_width=0

#fucntion to get the mask of head and body for the corropnding head and body
for i in range(0,3):
    img_path=f"D:\work\ML\image_processing\YOLO V8\dataset\input\img_{i}.jpg"
    mask_path=f"D:\work\ML\image_processing\YOLO V8\dataset\Categories\img_{i}.png"
    
    result=model.predict(source=img_path, show=True)

    mask_frame=cv2.imread(mask_path)
    img_fram=cv2.imread(img_path)

    #extracting corrdinates of head and body from model
    headCordinates=np.array(result[0].boxes.cpu().numpy().xyxy[1], dtype=np.uint32)
    bodyCosrdinates=np.array(result[0].boxes.cpu().numpy().xyxy[0], dtype=np.uint32)

    print(result[0].boxes.cpu().numpy().xyxy[1])
    print(result[0].boxes.cpu().numpy().xyxy[0])
    
    head_height+=headCordinates[3]-headCordinates[1]
    head_width+=headCordinates[2]-headCordinates[0]

    body_height+=bodyCosrdinates[3]-bodyCosrdinates[1]
    body_width+=bodyCosrdinates[2]-bodyCosrdinates[0]    

    #showing the head and body original image
    cv2.imshow("head img",get_img_part(img_fram,headCordinates))
    cv2.imshow("body img",get_img_part(img_fram,bodyCosrdinates))

    cv2.waitKey(0)
    

    # #showing the head and body mask image
    cv2.imshow("head img",get_img_part(mask_frame,headCordinates))
    cv2.imshow("body img",get_img_part(mask_frame,bodyCosrdinates))

    cv2.waitKey(0)



image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_0.jpg: 640x448 1 head, 1 body, 163.9ms
Speed: 3.0ms preprocess, 163.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
[     232.57      43.512      308.06       121.2]
[     182.11      123.48      336.39      577.21]

image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_1.jpg: 640x448 1 head, 1 body, 162.7ms
Speed: 3.0ms preprocess, 162.7ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 448)
[     102.51      98.725      305.54      593.65]
[     149.38      2.1381      244.06       99.27]

image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_2.jpg: 640x448 1 head, 1 body, 169.7ms
Speed: 3.0ms preprocess, 169.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
[     80.511           0      187.14      82.681]
[     52.123      64.412      221.89      588.18]


In [48]:
print(head_height/3)
print(head_width/3)
print(body_height/3)
print(body_width/3)

# head->240 by 140
# body->440 by 160

218.33333333333334
128.66666666666666
358.3333333333333
139.33333333333334


In [35]:
print(x1,y1)

tensor(31.2185) tensor(-47.2631)


In [10]:
cv2.imshow("img",result[0].orig_img)
cv2.waitKey(0)

-1

In [11]:
for res in result:
    a=res.boxes.cpu().numpy()
    #getting the corrdinates of bounding box for classes
    xyxys=a.xyxy
    c=False
    for xyxy in xyxys:
        if c:
            True
            continue
        print(xyxy)
        img1=cv2.rectangle(frame, (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (0,255,0), 1)
    cv2.imshow("img_", img1)
    cv2.waitKey(0)
    


[     109.76      153.17      266.85      554.03]
[     164.52      90.647       227.3      169.16]


In [12]:
arr=np.array(xyxys[0],dtype=np.uint16)
arr1=np.array(xyxys[1],dtype=np.uint16)

print(arr)
print(arr1)

[109 153 266 554]
[164  90 227 169]


In [44]:
def get_img_part(img,arr):
    """
    img: original image 
    arr: cordinates for subdivision
    """
    return img[arr[1]:arr[3],arr[0]:arr[2]]

In [14]:
body=frame[arr1[1]:arr1[3],arr1[0]:arr1[2]]
head=frame[arr1[1]:arr1[3],arr1[0]:arr1[2]]
print(head.shape)


(79, 63, 3)


In [15]:
cv2.imshow("temp img",head)
cv2.waitKey(0)

-1

In [16]:
cv2.imshow("temp img",get_img_part(frame,arr1))
cv2.waitKey(0)

-1

In [17]:
temparr=np.array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12],
    [13,14,15,16,17,18]
])

In [18]:
temparr[1:,:2]

array([[ 7,  8],
       [13, 14]])

In [7]:
for i in range(7998,8000):
    path=f"D:\work\ML\image_processing\YOLO V8\dataset\input\img_{i}.jpg"
    original_image=cv2.imread(path)
    result=model.predict(source=path, show=True)
    frame=result[0].orig_img
    a=result[0].boxes.cpu().numpy()
    #getting the corrdinates of bounding box for classes
    xyxys=a.xyxy
    c=False
    for xyxy in xyxys:
        if c:
            True
            continue
        print(xyxy)
        img1=cv2.rectangle(frame, (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (0,255,0), 1)
        framed_orginal_image=cv2.rectangle(original_image, (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (0,255,0), 1)
    cv2.imshow("img_outfile_from_NET", img1)
    cv2.imshow("img_outfile_from_original", framed_orginal_image)
    print(img1.shape)
    cv2.waitKey(0)



image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_7998.jpg: 640x448 1 head, 1 body, 161.1ms
Speed: 4.0ms preprocess, 161.1ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
[     176.63      85.494      233.31      163.06]
[     134.03      161.07      276.26      595.02]
(600, 400, 3)

image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_7999.jpg: 640x448 1 head, 1 body, 155.6ms
Speed: 4.5ms preprocess, 155.6ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 448)
[      133.2      159.75      270.86      557.78]
[     197.77      100.55      260.26       167.7]
(600, 400, 3)


In [8]:
for i in range(7998,8000):
    #reading the original image from path
    path=f"D:\work\ML\image_processing\YOLO V8\dataset\input\img_{i}.jpg"
    original_image=cv2.imread(path)

    #passing the image to the model
    result=model.predict(source=path, show=True)
    a=result[0].boxes.cpu().numpy()

    #getting the corrdinates of bounding box for classes
    xyxys=a.xyxy

    #building the bounding box
    for xyxy in xyxys:
        framed_orginal_image=cv2.rectangle(original_image, (int(xyxy[0]), int(xyxy[1])), (int(xyxy[2]), int(xyxy[3])), (0,255,0), 1)

    cv2.imshow("img_outfile_from_original", framed_orginal_image)
    cv2.waitKey(0)



image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_7998.jpg: 640x448 1 head, 1 body, 162.5ms
Speed: 3.0ms preprocess, 162.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
(600, 400, 3)

image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_7999.jpg: 640x448 1 head, 1 body, 163.6ms
Speed: 5.0ms preprocess, 163.6ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 448)
(600, 400, 3)


# production code

In [14]:
# fuction to get original image preditciton and its corrosponding head and body img
for i in range(0,2):
    path=f"D:\work\ML\image_processing\YOLO V8\dataset\input\img_{i}.jpg"
    result=model.predict(source=path, show=True)
    frame=cv2.imread(path)
    headCordinates=np.array(result[0].boxes.cpu().numpy().xyxy[1], dtype=np.uint32)
    bodyCosrdinates=np.array(result[0].boxes.cpu().numpy().xyxy[0], dtype=np.uint32)
    cv2.imshow("head img",get_img_part(frame,headCordinates))
    cv2.imshow("body img",get_img_part(frame,bodyCosrdinates))
    cv2.waitKey(0)


image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_0.jpg: 640x448 1 head, 1 body, 155.6ms
Speed: 3.0ms preprocess, 155.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)

image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_1.jpg: 640x448 1 head, 1 body, 159.9ms
Speed: 2.0ms preprocess, 159.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)


In [21]:
#fucntion to get the mask of head and body for the corropnding head and body
for i in range(0,3):
    img_path=f"D:\work\ML\image_processing\YOLO V8\dataset\input\img_{i}.jpg"
    mask_path=f"D:\work\ML\image_processing\YOLO V8\dataset\Categories\img_{i}.png"
    
    result=model.predict(source=img_path, show=True)

    mask_frame=cv2.imread(mask_path)
    img_fram=cv2.imread(img_path)

    #extracting corrdinates of head and body from model
    headCordinates=np.array(result[0].boxes.cpu().numpy().xyxy[1], dtype=np.uint32)
    bodyCosrdinates=np.array(result[0].boxes.cpu().numpy().xyxy[0], dtype=np.uint32)


    #showing the head and body original image
    cv2.imshow("head img",get_img_part(img_fram,headCordinates))
    cv2.imshow("body img",get_img_part(img_fram,bodyCosrdinates))

    cv2.waitKey(0)
    

    # #showing the head and body mask image
    cv2.imshow("head img",get_img_part(mask_frame,headCordinates))
    cv2.imshow("body img",get_img_part(mask_frame,bodyCosrdinates))

    cv2.waitKey(0)







image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_0.jpg: 640x448 1 head, 1 body, 178.0ms
Speed: 4.0ms preprocess, 178.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 448)
[     232.57      43.512      308.06       121.2]
[     182.11      123.48      336.39      577.21]

image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_1.jpg: 640x448 1 head, 1 body, 169.1ms
Speed: 3.0ms preprocess, 169.1ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
[     102.51      98.725      305.54      593.65]
[     149.38      2.1381      244.06       99.27]

image 1/1 D:\work\ML\image_processing\YOLO V8\dataset\input\img_2.jpg: 640x448 1 head, 1 body, 164.6ms
Speed: 3.0ms preprocess, 164.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 448)
[     80.511           0      187.14      82.681]
[     52.123      64.412      221.89      588.18]


# head parsing network code

In [5]:
# input image form above model will be resized to (480, ,280 , 3)



import tensorflow as tf

def fcn8(input_shape=(320, 192, 3), num_classes=21):
    inputs = tf.keras.layers.Input(shape=input_shape)

    # Block 1
    x = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
    x = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Block 2
    x = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Block 3
    x = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Block 4
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Block 5
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Fully Convolutional Layers (FC Layers)
    x = tf.keras.layers.Conv2D(4096, (7, 7), activation='relu', padding='same')(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    x = tf.keras.layers.Conv2D(4096, (1, 1), activation='relu', padding='same')(x)
    x = tf.keras.layers.Dropout(0.5)(x)

    # Classification layer (output layer)
    x = tf.keras.layers.Conv2D(num_classes, (1, 1), activation='softmax', padding='same')(x)

    # Upsampling for FCN-8
    x = tf.keras.layers.Conv2DTranspose(num_classes, kernel_size=(4, 4), strides=(2, 2), padding='same')(x)
    x = tf.keras.layers.Conv2DTranspose(num_classes, kernel_size=(4, 4), strides=(2, 2), padding='same')(x)
    x = tf.keras.layers.Conv2DTranspose(num_classes, kernel_size=(16, 16), strides=(8, 8), padding='same')(x)

    model = tf.keras.Model(inputs=inputs, outputs=x)
    return model

# Example usage:
model = fcn8(input_shape=(320, 192, 3), num_classes=21)
model.summary()






# body parsing network

In [ ]:
import tensorflow as tf

def fcn8(input_shape=(640, 384, 3), num_classes=21):
    inputs = tf.keras.layers.Input(shape=input_shape)

    # Block 1
    x = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same')(inputs)
    x = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Block 2
    x = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Block 3
    x = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Block 4
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Block 5
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
    x = tf.keras.layers.MaxPooling2D((2, 2), strides=(2, 2))(x)

    # Fully Convolutional Layers (FC Layers)
    x = tf.keras.layers.Conv2D(4096, (7, 7), activation='relu', padding='same')(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    x = tf.keras.layers.Conv2D(4096, (1, 1), activation='relu', padding='same')(x)
    x = tf.keras.layers.Dropout(0.5)(x)

    # Classification layer (output layer)
    x = tf.keras.layers.Conv2D(num_classes, (1, 1), activation='softmax', padding='same')(x)

    # Upsampling for FCN-8
    x = tf.keras.layers.Conv2DTranspose(num_classes, kernel_size=(4, 4), strides=(2, 2), padding='same')(x)
    x = tf.keras.layers.Conv2DTranspose(num_classes, kernel_size=(4, 4), strides=(2, 2), padding='same')(x)
    x = tf.keras.layers.Conv2DTranspose(num_classes, kernel_size=(16, 16), strides=(8, 8), padding='same')(x)

    model = tf.keras.Model(inputs=inputs, outputs=x)
    return model

# Example usage:
model = fcn8(input_shape=(640, 384, 3), num_classes=21)
model.summary()


# training parameters



In [ ]:
import tensorflow as tf

# Define your FCN-8 model (assuming you've already defined `fcn8` function as provided earlier)
model = fcn8(input_shape=(640, 384, 3), num_classes=21)

# Define your loss function (e.g., categorical crossentropy for multi-class segmentation)
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()

# Define optimizer with momentum and weight decay
optimizer = tf.keras.optimizers.SGD(learning_rate=0.0001, momentum=0.9, decay=0.0005)

# Compile the model
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

# Prepare dummy data (replace with your actual data loading and preprocessing)
import numpy as np
x_train = np.random.randn(100, 640, 384, 3)  # example random input data
y_train = np.random.randint(0, 21, size=(100, 640, 384))  # example random labels

# Dummy training loop (replace with your actual training loop)
batch_size = 10
epochs = 10

for epoch in range(epochs):
    print(f"Epoch {epoch+1}/{epochs}:")
    for i in range(0, len(x_train), batch_size):
        x_batch = x_train[i:i+batch_size]
        y_batch = y_train[i:i+batch_size]
        
        # Forward pass
        with tf.GradientTape() as tape:
            logits = model(x_batch, training=True)
            loss_value = loss_fn(y_batch, logits)
        
        # Backward pass
        gradients = tape.gradient(loss_value, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
        
        # Print batch loss (optional)
        print(f"  Batch {i//batch_size+1}/{len(x_train)//batch_size}, Loss: {loss_value.numpy():.4f}")

# Evaluate the model (optional)
# Replace x_test and y_test with your test data
# loss, accuracy = model.evaluate(x_test, y_test)
# print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")
